### ISSUE TITLE
Order book doesn't support "i" messages for initial snapshot

### ISSUE THREAD

**Issue by jbrukh** [iowar/poloniex#1]
As described here: https://docs.poloniex.com/#price-aggregated-book

This package supports "o" and "t" messages, but not "i" messages. (See `push.go` in the section where you're converting incoming websocket messages after having subscribed to a particlar market.)

**Comment by iowar** [comment]
When this package was written, Poloniex didn't have a good documentation about Push API. Therefore the push.go was written by examining the js codes in the Poloniex site. But now many bug fixed and package rewritten. check https://github.com/iowar/poloniex/commit/a1e7e021269ec771caf06b59d3811179b32d0308

**Comment by jbrukh** [comment]
Thank you for your quick response, I will check out the master branch code.

I have proposed a PR to add Go modules support to your package, so it may be more easily consumed: https://github.com/iowar/poloniex/pull/2

Thanks!
